"""Tests for the print-readiness upgrade: printer's marks, ICC-managed
CMYK, custom/panel formats, multi-page output and dieline passthrough.
PDFs are verified by inspecting the generated bytes and decompressed
content streams, the same way the writer's existing tests work."""

import re
import zlib

import pytest

from designer.cli import main as cli_main
from designer.formats import get_format
from designer.render import render_pdf
from designer.svg import Document, GradientDef, Shape


def pdf_streams(data: bytes) -> bytes:
    """All stream contents, decompressed where Flate-encoded."""
    out = b""
    for m in re.finditer(rb"stream\r?\n(.*?)endstream", data, re.DOTALL):
        chunk = m.group(1).strip(b"\r\n")
        try:
            out += zlib.decompress(chunk)
        except zlib.error:
            out += chunk
    return out


def media_box(data: bytes) -> tuple[float, float, float, float]:
    m = re.search(rb"/MediaBox \[([\d. ]+)\]", data)
    assert m, "no MediaBox"
    vals = [float(v) for v in m.group(1).split()]
    return tuple(vals)


def card_doc() -> Document:
    return Document(width=336, height=192, shapes=[
        Shape("rect", {"x": "-9", "y": "-9", "width": "354", "height": "210",
                       "fill": "#1a56db"}),
        Shape("text", {"x": "20", "y": "100", "font-size": "16", "fill": "#ffffff",
                       "font-family": "DejaVu Sans"}, text="ACME"),
    ])


# ----------------------------------------------------------- printer's marks


def test_marks_grow_page_and_record_trim(tmp_path):
    spec = get_format("business-card")
    out = render_pdf(card_doc(), tmp_path / "card.pdf",
                     format=spec, bleed=9, marks=True)
    data = out.read_bytes()
    assert b"/TrimBox" in data and b"/BleedBox" in data
    # Page = trim + 2 * (bleed + 10mm slug), at 96dpi px, 0.75pt/px.
    slug = 10.0 * 96 / 25.4
    expected_w = (336 + 2 * (9 + slug)) * 0.75
    x0, y0, x1, y1 = media_box(data)
    assert x1 == pytest.approx(expected_w, abs=0.1)
    # Crop-mark strokes and the job slug line are in the content.
    ops = pdf_streams(data)
    assert ops.count(b" l S") >= 8          # 8 crop marks + reg crosshairs
    assert b"untitled" in ops               # slug: no source -> placeholder
    assert b"RGB" in ops                    # slug names the colorspace


def test_marks_off_keeps_page_at_trim(tmp_path):
    out = render_pdf(card_doc(), tmp_path / "flat.pdf")
    data = out.read_bytes()
    assert b"/TrimBox" not in data
    x0, y0, x1, y1 = media_box(data)
    assert x1 == pytest.approx(336 * 0.75, abs=0.01)
    assert y1 == pytest.approx(192 * 0.75, abs=0.01)


def test_bleed_without_marks_grows_page_to_bleed(tmp_path):
    out = render_pdf(card_doc(), tmp_path / "bled.pdf", bleed=9)
    data = out.read_bytes()
    assert b"/TrimBox" in data
    x0, y0, x1, y1 = media_box(data)
    assert x1 == pytest.approx((336 + 18) * 0.75, abs=0.01)


def test_cmyk_marks_use_registration_color(tmp_path):
    spec = get_format("business-card")
    out = render_pdf(card_doc(), tmp_path / "reg.pdf",
                     format=spec, bleed=9, marks=True, cmyk=True)
    ops = pdf_streams(out.read_bytes())
    assert b"1 1 1 1 K" in ops    # marks stroke on every separation
    assert b"1 1 1 1 k" in ops    # slug text too


def test_artwork_is_clipped_to_the_bleed_box(tmp_path):
    out = render_pdf(card_doc(), tmp_path / "clip.pdf", bleed=9, marks=True)
    ops = pdf_streams(out.read_bytes())
    assert b"-9.000 -9.000 354.000 210.000 re\nW n" in ops


def test_pdf_text_is_upright_and_gradients_unflipped(tmp_path):
    doc = Document(width=200, height=200)
    doc.defs.append(GradientDef(id="g", kind="linear",
                                stops=[(0.0, "#000000"), (1.0, "#ff0000")],
                                coords={"x1": 0, "y1": 0, "x2": 0, "y2": 200}))
    doc.shapes.append(Shape("rect", {"x": "0", "y": "0", "width": "200",
                                     "height": "200", "fill": "url(#g)"}))
    doc.shapes.append(Shape("text", {"x": "20", "y": "190", "font-size": "20",
                                     "fill": "#ffffff", "font-family": "DejaVu Sans"},
                            text="BOTTOM"))
    data = render_pdf(doc, tmp_path / "up.pdf").read_bytes()
    ops = pdf_streams(data)
    # Text matrix counter-flips the y-flipped content stream.
    assert b"1 0 0 -1 20.000 190.000 Tm" in ops
    # Shading coords are document coords: y runs 0 -> 200, not 200 -> 0.
    assert b"/Coords [0.000 0.000 0.000 200.000]" in data


def test_cli_marks_default_on_for_print_with_bleed(tmp_path, capsys):
    svg = tmp_path / "card.svg"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 336 192">'
        '<rect x="0" y="0" width="336" height="192" fill="#1a56db"/></svg>'
    )
    system = tmp_path / "sys.yaml"
    system.write_text(
        "name: T\ncolor:\n  tokens:\n    primary: '#1a56db'\n"
        "print:\n  bleed: 9\n"
    )
    out = tmp_path / "card.pdf"
    assert cli_main(["render", str(svg), "-o", str(out),
                     "--format", "business-card", "--system", str(system)]) == 0
    assert b"/TrimBox" in out.read_bytes()
    # And explicitly off:
    out2 = tmp_path / "card2.pdf"
    assert cli_main(["render", str(svg), "-o", str(out2), "--no-marks",
                     "--format", "business-card", "--system", str(system)]) == 0
    data2 = out2.read_bytes()
    assert b"untitled" not in pdf_streams(data2)
    assert pdf_streams(data2).count(b" l S") == 0
