# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Tests for the print-readiness upgrade: printer's marks, ICC-managed
CMYK, custom/panel formats, multi-page output and dieline passthrough.
PDFs are verified by inspecting the generated bytes and decompressed
content streams, the same way the writer's existing tests work."""

import base64
import io
import re
import struct
import zlib

import pytest

from designer.cli import main as cli_main
from designer.formats import get_format
from designer.render import render_pdf
from designer.svg import Document, GradientDef, Shape
from designer.tokens import system_from_dict


def pdf_streams(data: bytes) -> bytes:
    """All stream contents, decompressed where Flate-encoded. Streams
    are sliced by their declared /Length: compressed bytes may contain
    'endstream' by coincidence."""
    out = b""
    for m in re.finditer(rb"/Length (\d+)[^>]*>>\s*stream\r?\n", data):
        chunk = data[m.end():m.end() + int(m.group(1))]
        try:
            out += zlib.decompress(chunk)
        except zlib.error:
            out += chunk
    return out


def media_box(data: bytes) -> tuple[float, float, float, float]:
    m = re.search(rb"/MediaBox \[([\d. ]+)\]", data)
    assert m, "no MediaBox"
    vals = [float(v) for v in m.group(1).split()]
    return tuple(vals)


def card_doc() -> Document:
    return Document(width=336, height=192, shapes=[
        Shape("rect", {"x": "-9", "y": "-9", "width": "354", "height": "210",
                       "fill": "#1a56db"}),
        Shape("text", {"x": "20", "y": "100", "font-size": "16", "fill": "#ffffff",
                       "font-family": "DejaVu Sans"}, text="ACME"),
    ])


# ----------------------------------------------------------- printer's marks


def test_marks_grow_page_and_record_trim(tmp_path):
    spec = get_format("business-card")
    out = render_pdf(card_doc(), tmp_path / "card.pdf",
                     format=spec, bleed=9, marks=True)
    data = out.read_bytes()
    assert b"/TrimBox" in data and b"/BleedBox" in data
    # Page = trim + 2 * (bleed + 10mm slug), at 96dpi px, 0.75pt/px.
    slug = 10.0 * 96 / 25.4
    expected_w = (336 + 2 * (9 + slug)) * 0.75
    x0, y0, x1, y1 = media_box(data)
    assert x1 == pytest.approx(expected_w, abs=0.1)
    # Crop-mark strokes and the job slug line are in the content.
    ops = pdf_streams(data)
    assert ops.count(b" l S") >= 8          # 8 crop marks + reg crosshairs
    assert b"untitled" in ops               # slug: no source -> placeholder
    assert b"RGB" in ops                    # slug names the colorspace


def test_marks_off_keeps_page_at_trim(tmp_path):
    out = render_pdf(card_doc(), tmp_path / "flat.pdf")
    data = out.read_bytes()
    assert b"/TrimBox" not in data
    x0, y0, x1, y1 = media_box(data)
    assert x1 == pytest.approx(336 * 0.75, abs=0.01)
    assert y1 == pytest.approx(192 * 0.75, abs=0.01)


def test_bleed_without_marks_grows_page_to_bleed(tmp_path):
    out = render_pdf(card_doc(), tmp_path / "bled.pdf", bleed=9)
    data = out.read_bytes()
    assert b"/TrimBox" in data
    x0, y0, x1, y1 = media_box(data)
    assert x1 == pytest.approx((336 + 18) * 0.75, abs=0.01)


def test_cmyk_marks_use_registration_color(tmp_path):
    spec = get_format("business-card")
    out = render_pdf(card_doc(), tmp_path / "reg.pdf",
                     format=spec, bleed=9, marks=True, cmyk=True)
    ops = pdf_streams(out.read_bytes())
    assert b"1 1 1 1 K" in ops    # marks stroke on every separation
    assert b"1 1 1 1 k" in ops    # slug text too


def test_artwork_is_clipped_to_the_bleed_box(tmp_path):
    out = render_pdf(card_doc(), tmp_path / "clip.pdf", bleed=9, marks=True)
    ops = pdf_streams(out.read_bytes())
    assert b"-9.000 -9.000 354.000 210.000 re\nW n" in ops


def test_pdf_text_is_upright_and_gradients_unflipped(tmp_path):
    doc = Document(width=200, height=200)
    doc.defs.append(GradientDef(id="g", kind="linear",
                                stops=[(0.0, "#000000"), (1.0, "#ff0000")],
                                coords={"x1": 0, "y1": 0, "x2": 0, "y2": 200}))
    doc.shapes.append(Shape("rect", {"x": "0", "y": "0", "width": "200",
                                     "height": "200", "fill": "url(#g)"}))
    doc.shapes.append(Shape("text", {"x": "20", "y": "190", "font-size": "20",
                                     "fill": "#ffffff", "font-family": "DejaVu Sans"},
                            text="BOTTOM"))
    data = render_pdf(doc, tmp_path / "up.pdf").read_bytes()
    ops = pdf_streams(data)
    # Text matrix counter-flips the y-flipped content stream.
    assert b"1 0 0 -1 20.000 190.000 Tm" in ops
    # Shading coords are document coords: y runs 0 -> 200, not 200 -> 0.
    assert b"/Coords [0.000 0.000 0.000 200.000]" in data


# ------------------------------------------------------ ICC-managed CMYK
#
# Pillow's ImageCms cannot create a CMYK profile, so the managed path is
# tested against a minimal hand-built CMYK output profile (lut8 A2B0/B2A0
# with a crude Lab<->CMYK mapping). It is not colorimetrically meaningful
# — it only has to be a profile lcms accepts, so the test proves colors
# really travel through the transform.


def _desc_tag(text: str) -> bytes:
    ascii_ = text.encode("ascii") + b"\x00"
    return (b"desc" + b"\x00" * 4 + struct.pack(">I", len(ascii_)) + ascii_
            + b"\x00" * 10 + b"\x00" * 67)


def _xyz_tag(x: float, y: float, z: float) -> bytes:
    return b"XYZ " + b"\x00" * 4 + b"".join(
        struct.pack(">i", int(round(v * 65536))) for v in (x, y, z)
    )


def _lut8_tag(in_ch: int, out_ch: int, grid: int, fn) -> bytes:
    head = b"mft1" + b"\x00" * 4 + bytes([in_ch, out_ch, grid, 0])
    matrix = b"".join(
        struct.pack(">i", 65536 if r == c else 0) for r in range(3) for c in range(3)
    )
    clut = bytearray()

    def rec(dim, coords):
        if dim == in_ch:
            for v in fn([c / (grid - 1) for c in coords]):
                clut.append(int(round(max(0.0, min(1.0, v)) * 255)))
            return
        for i in range(grid):
            rec(dim + 1, coords + [i])

    rec(0, [])
    return (head + matrix + bytes(range(256)) * in_ch + bytes(clut)
            + bytes(range(256)) * out_ch)


def make_cmyk_profile() -> bytes:
    def b2a(lab):
        L, a, b = lab[0], lab[1] - 0.5, lab[2] - 0.5
        return [max(0.0, -a * 2), max(0.0, a * 2), max(0.0, b * 2), 1 - L]

    def a2b(cmyk):
        c, m, y, k = cmyk
        return [(1 - k) * (1 - 0.5 * (c + m + y) / 3),
                (m - c) / 2 + 0.5, y / 2 + 0.5]

    tags = [
        (b"desc", _desc_tag("designer test CMYK")),
        (b"cprt", b"text" + b"\x00" * 4 + b"none\x00"),
        (b"wtpt", _xyz_tag(0.9642, 1.0, 0.8249)),
        (b"A2B0", _lut8_tag(4, 3, 4, a2b)),
        (b"B2A0", _lut8_tag(3, 4, 8, b2a)),
    ]
    table = struct.pack(">I", len(tags))
    offset = 128 + 4 + 12 * len(tags)
    body = b""
    for sig, data in tags:
        pad = (4 - len(data) % 4) % 4
        table += sig + struct.pack(">II", offset, len(data))
        body += data + b"\x00" * pad
        offset += len(data) + pad
    header = struct.pack(
        ">I4sI4s4s4s12s4s", 128 + len(table) + len(body), b"lcms",
        0x02400000, b"prtr", b"CMYK", b"Lab ",
        b"\x07\xd0\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00", b"acsp",
    )
    header += b"\x00" * (68 - len(header))
    header += struct.pack(">III", int(0.9642 * 65536), 65536, int(0.8249 * 65536))
    header += b"\x00" * (128 - len(header))
    return header + table + body


@pytest.fixture()
def cmyk_profile(tmp_path):
    path = tmp_path / "press.icc"
    path.write_bytes(make_cmyk_profile())
    try:
        from PIL import ImageCms

        ImageCms.buildTransformFromOpenProfiles(
            ImageCms.createProfile("sRGB"),
            ImageCms.getOpenProfile(str(path)), "RGB", "CMYK",
        )
    except Exception:
        pytest.skip("littlecms unavailable or rejects the test profile")
    return path


def _data_uri_image() -> str:
    from PIL import Image

    buf = io.BytesIO()
    Image.new("RGB", (8, 8), (26, 86, 219)).save(buf, "PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def test_icc_profile_parses_from_system_yaml():
    system = system_from_dict({
        "name": "P",
        "color": {"tokens": {"ink": "#111827"}},
        "print": {"icc_profile": "profiles/press.icc"},
    })
    assert system.icc_profile == "profiles/press.icc"


def test_icc_managed_cmyk_embeds_output_intent(tmp_path, cmyk_profile):
    doc = card_doc()
    doc.shapes.append(Shape("image", {
        "x": "10", "y": "10", "width": "8", "height": "8",
        "href": _data_uri_image(),
    }))
    out = render_pdf(doc, tmp_path / "press.pdf", cmyk=True,
                     icc_profile=cmyk_profile)
    data = out.read_bytes()
    assert b"/OutputIntents" in data
    assert b"/DestOutputProfile" in data
    assert b"(designer test CMYK)" in data
    # Embedded raster travels through the same transform.
    assert b"/ColorSpace /DeviceCMYK" in data
    # No unmanaged warning when the profile works.
    assert not any("unmanaged" in w for w in doc.warnings)
    # The managed conversion differs from the naive formula.
    from designer.rules.print_rules import rgb_to_cmyk

    ops = pdf_streams(data)
    naive = " ".join(f"{v:.4f}" for v in rgb_to_cmyk((26, 86, 219))) + " k"
    assert naive.encode() not in ops
    assert re.search(rb"[\d.]+ [\d.]+ [\d.]+ [\d.]+ k", ops)


def test_cmyk_without_profile_warns_unmanaged(tmp_path):
    doc = card_doc()
    data = render_pdf(doc, tmp_path / "proof.pdf", cmyk=True).read_bytes()
    assert b"/OutputIntents" not in data
    assert any("unmanaged" in w for w in doc.warnings)


def test_broken_profile_falls_back_and_warns(tmp_path):
    bad = tmp_path / "bad.icc"
    bad.write_bytes(b"not a profile")
    doc = card_doc()
    render_pdf(doc, tmp_path / "fallback.pdf", cmyk=True, icc_profile=bad)
    assert any("could not be used" in w for w in doc.warnings)


# --------------------------------------------------- custom/panel formats


def test_builtin_print_presets():
    board = get_format("signboard-2000x800")
    assert board.category == "print" and board.dpi == 150
    assert board.width == pytest.approx(2000 * 150 / 25.4, abs=0.5)
    assert board.height == pytest.approx(800 * 150 / 25.4, abs=0.5)

    zfold = get_format("z-fold-a4")
    assert len(zfold.panels) == 3
    assert sum(zfold.panels) == pytest.approx(zfold.width, abs=1.0)
    # The fold-in panel is 2mm narrower than the cover panel.
    assert zfold.panels[0] - zfold.panels[2] == pytest.approx(2 * 300 / 25.4, abs=0.5)

    folder = get_format("corporate-folder-a4")
    assert folder.panels[1] == pytest.approx(5 * 300 / 25.4, abs=0.5)  # spine
    assert folder.panels_y[-1] == pytest.approx(80 * 300 / 25.4, abs=0.5)  # pocket


def test_custom_formats_from_system_yaml_merge_into_catalog():
    from designer.engine import ComplianceEngine

    system = system_from_dict({
        "name": "Shop",
        "color": {"tokens": {"ink": "#111827"}},
        "formats": {
            "shelf-strip": {
                "unit": "mm", "dpi": 300, "width": 1000, "height": 60,
                "category": "print", "bleed": 3,
                "description": "shelf-edge strip",
            },
        },
    })
    spec = get_format("shelf-strip", extra=system.formats)
    assert spec.width == pytest.approx(1000 * 300 / 25.4, abs=0.5)
    assert spec.bleed == pytest.approx(3 * 300 / 25.4, abs=0.5)
    engine = ComplianceEngine(system, format="shelf-strip")
    assert engine.format.name == "shelf-strip"
    # Unknown names still fail, and customs never leak without the system.
    with pytest.raises(ValueError, match="Known formats"):
        get_format("shelf-strip")


def test_custom_format_requires_dimensions():
    with pytest.raises(ValueError, match="width and height"):
        system_from_dict({
            "name": "S",
            "color": {"tokens": {"ink": "#111827"}},
            "formats": {"broken": {"category": "print"}},
        })


def test_cli_formats_lists_custom_formats(tmp_path, capsys):
    system = tmp_path / "sys.yaml"
    system.write_text(
        "name: T\ncolor:\n  tokens:\n    primary: '#1a56db'\n"
        "formats:\n  gazebo-panel:\n    unit: mm\n    dpi: 150\n"
        "    width: 2900\n    height: 2100\n    category: print\n"
    )
    assert cli_main(["formats", "--system", str(system)]) == 0
    out = capsys.readouterr().out
    assert "gazebo-panel" in out
    assert "signboard-2000x800" in out


def test_fold_marks_at_panel_boundaries(tmp_path):
    spec = get_format("z-fold-a4")
    doc = Document(width=spec.width, height=spec.height, shapes=[
        Shape("rect", {"x": "0", "y": "0", "width": f"{spec.width}",
                       "height": f"{spec.height}", "fill": "#f3f4f6"}),
    ])
    out = render_pdf(doc, tmp_path / "fold.pdf", format=spec, marks=True)
    ops = pdf_streams(out.read_bytes())
    assert re.search(rb"\[[\d.]+ [\d.]+\] 0 d", ops)  # dashed pattern set
    # Two fold boundaries, ticked top and bottom, at the panel sums.
    x1, x2 = spec.panels[0], spec.panels[0] + spec.panels[1]
    for x in (x1, x2):
        assert ops.count(f"{x:.3f} ".encode()) >= 2
    # Physical size: A4 landscape trim -> 842pt-wide TrimBox at 300dpi.
    m = re.search(rb"/TrimBox \[([-\d. ]+)\]", out.read_bytes())
    t = [float(v) for v in m.group(1).split()]
    assert t[2] - t[0] == pytest.approx(841.9, abs=0.5)


def test_folder_pocket_gets_horizontal_fold_marks(tmp_path):
    spec = get_format("corporate-folder-a4")
    doc = Document(width=spec.width, height=spec.height, shapes=[
        Shape("rect", {"x": "0", "y": "0", "width": f"{spec.width}",
                       "height": f"{spec.height}", "fill": "#ffffff"}),
    ])
    ops = pdf_streams(
        render_pdf(doc, tmp_path / "folder.pdf", format=spec, marks=True).read_bytes()
    )
    pocket_y = spec.panels_y[0]
    assert ops.count(f"{pocket_y:.3f} ".encode()) >= 1


# ------------------------------------------------------------- multi-page


def test_document_list_makes_multi_page_pdf(tmp_path):
    front = card_doc()
    back = Document(width=336, height=192, shapes=[
        Shape("rect", {"x": "0", "y": "0", "width": "336", "height": "192",
                       "fill": "#111827"}),
        Shape("text", {"x": "20", "y": "100", "font-size": "12", "fill": "#ffffff",
                       "font-family": "DejaVu Sans"}, text="back side"),
    ])
    out = render_pdf([front, back], tmp_path / "two.pdf",
                     format=get_format("business-card"), bleed=9, marks=True)
    data = out.read_bytes()
    assert data.count(b"/Type /Page ") == 2
    assert b"/Count 2" in data
    assert data.count(b"/TrimBox") == 2  # marks/boxes on every page
    ops = pdf_streams(data)
    assert b"ACME" in ops and b"back side" in ops


def test_empty_document_list_is_an_error(tmp_path):
    from designer.render import RenderError

    with pytest.raises(RenderError):
        render_pdf([], tmp_path / "none.pdf")


def test_cli_renders_front_and_back(tmp_path):
    front = tmp_path / "front.svg"
    back = tmp_path / "back.svg"
    for path, color in ((front, "#1a56db"), (back, "#111827")):
        path.write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 336 192">'
            f'<rect x="0" y="0" width="336" height="192" fill="{color}"/></svg>'
        )
    out = tmp_path / "board.pdf"
    assert cli_main(["render", str(front), str(back), "-o", str(out),
                     "--format", "business-card", "--marks"]) == 0
    data = out.read_bytes()
    assert b"/Count 2" in data
    ops = pdf_streams(data)
    assert b"front.svg" in ops and b"back.svg" in ops  # per-page slug


def test_cli_rejects_multiple_inputs_for_png(tmp_path, capsys):
    svg = tmp_path / "a.svg"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">'
        '<rect x="0" y="0" width="10" height="10" fill="#1a56db"/></svg>'
    )
    assert cli_main(["render", str(svg), str(svg),
                     "-o", str(tmp_path / "x.png")]) == 2
    assert "multiple inputs" in capsys.readouterr().err


# --------------------------------------------------- dieline passthrough


DIELINE_SVG = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">'
    '<rect x="0" y="0" width="200" height="200" fill="#e01111"/>'
    '<g id="dieline">'
    '<rect x="10" y="10" width="180" height="180" fill="none" '
    'stroke="#ff00ff" stroke-width="0.5"/>'
    "</g></svg>"
)


def dieline_doc(tmp_path) -> Document:
    from designer.svg import parse_svg

    path = tmp_path / "die.svg"
    path.write_text(DIELINE_SVG)
    return parse_svg(path)


def test_dieline_group_is_marked_on_parse(tmp_path):
    from designer.svg import is_dieline, parse_svg, save

    doc = dieline_doc(tmp_path)
    flags = [is_dieline(s) for s in doc.shapes]
    assert flags == [False, True]
    # Survives a round-trip through the serializer.
    out = tmp_path / "roundtrip.svg"
    save(doc, out)
    again = parse_svg(out)
    assert [is_dieline(s) for s in again.shapes] == [False, True]
    # class="dieline" works too
    p2 = tmp_path / "cls.svg"
    p2.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">'
        '<path class="dieline vendor" d="M 0 0 L 10 0 L 10 10 Z" '
        'stroke="#000" fill="none"/></svg>'
    )
    assert is_dieline(parse_svg(p2).shapes[0])


def test_rules_never_touch_dielines(tmp_path):
    from designer.engine import ComplianceEngine
    from designer.svg import is_dieline
    from designer.tokens import load_system

    doc = dieline_doc(tmp_path)
    # Off-palette hairline stroke: PaletteRule/StrokeWidthRule/print
    # hairline would all rewrite this if it were artwork.
    engine = ComplianceEngine(load_system(), format="business-card")
    report = engine.comply(doc)
    die = next(s for s in doc.shapes if is_dieline(s))
    assert die.get("stroke") == "#ff00ff"
    assert die.numeric("stroke-width") == 0.5
    die_msgs = [f for f in report.findings if "dieline" in (f.message or "")]
    assert not die_msgs
    assert len(doc.shapes) == 2  # excluded and re-appended, never dropped


def test_dieline_renders_stroke_only_png(tmp_path):
    from designer.render import render_png

    doc = dieline_doc(tmp_path)
    img = render_png(doc, None, supersample=1)
    assert img.getpixel((10, 100)) == (255, 0, 255)   # contour stroked
    assert img.getpixel((100, 100)) == (224, 17, 17)  # interior untouched


def test_dieline_rgb_pdf_uses_dedicated_stroke(tmp_path):
    doc = dieline_doc(tmp_path)
    data = render_pdf(doc, tmp_path / "die.pdf").read_bytes()
    ops = pdf_streams(data)
    assert b"1.0000 0.0000 1.0000 RG" in ops
    # Stroke only: the dieline never contributes a fill.
    assert ops.count(b"f*") == 1  # background rect only


def test_dieline_cmyk_pdf_gets_cutcontour_separation(tmp_path):
    doc = dieline_doc(tmp_path)
    data = render_pdf(doc, tmp_path / "cut.pdf", cmyk=True).read_bytes()
    assert b"/Separation /CutContour /DeviceCMYK" in data
    assert b"/OP true" in data  # overprint so the cut doesn't knock out art
    ops = pdf_streams(data)
    assert b"/CSCut CS" in ops and b"1 SCN" in ops


def test_cli_marks_default_on_for_print_with_bleed(tmp_path, capsys):
    svg = tmp_path / "card.svg"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 336 192">'
        '<rect x="0" y="0" width="336" height="192" fill="#1a56db"/></svg>'
    )
    system = tmp_path / "sys.yaml"
    system.write_text(
        "name: T\ncolor:\n  tokens:\n    primary: '#1a56db'\n"
        "print:\n  bleed: 9\n"
    )
    out = tmp_path / "card.pdf"
    assert cli_main(["render", str(svg), "-o", str(out),
                     "--format", "business-card", "--system", str(system)]) == 0
    assert b"/TrimBox" in out.read_bytes()
    # And explicitly off:
    out2 = tmp_path / "card2.pdf"
    assert cli_main(["render", str(svg), "-o", str(out2), "--no-marks",
                     "--format", "business-card", "--system", str(system)]) == 0
    data2 = out2.read_bytes()
    assert b"untitled" not in pdf_streams(data2)
    assert pdf_streams(data2).count(b" l S") == 0
